---
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
name: docs

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-20.04
    steps:
    - name: get ref name
      run: echo FOLDERNAME=${GITHUB_REF#refs/*/} >> $GITHUB_ENV

    - name: checkout code
      uses: actions/checkout@v2

    - name: hide token, no need for it here
      run: rm .npmrc

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: "15"

    - name: ðŸ¤”
      run: npm i -g ponpon@1.0.1

    - name: install dependencies
      run: ponpon i

    - name: quick type check
      run: npx tsc --noEmit

    - name: render docs
      run: ponpon run docs

    - name: deploy docs
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
        CLEAN: false
